/*
 * Waiting List Api
 *
 * Ambulance Waiting List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xnemecm1@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

 package ambulance_wl

import (
   "net/http"

   "github.com/gin-gonic/gin"
)

type AmbulanceConditionsAPI interface {

   // internal registration of api routes
   addRoutes(routerGroup *gin.RouterGroup)

    // AddConditions - Adds predefined conditions
   AddConditions(ctx *gin.Context)

    // DeleteConditions - Deletes all predefined conditions
   DeleteConditions(ctx *gin.Context)

    // GetConditions - Provides the list of conditions associated with ambulance
   GetConditions(ctx *gin.Context)

    // UpdateConditions - Updates predefined conditions
   UpdateConditions(ctx *gin.Context)

 }

 // partial implementation of AmbulanceConditionsAPI - all functions must be implemented in add on files
 type implAmbulanceConditionsAPI struct {

 }

 func newAmbulanceConditionsAPI() AmbulanceConditionsAPI {
   return &implAmbulanceConditionsAPI{}
 }

 func (this *implAmbulanceConditionsAPI) addRoutes(routerGroup *gin.RouterGroup) {
   routerGroup.Handle( http.MethodPost, "/waiting-list/:ambulanceId/condition", this.AddConditions)
   routerGroup.Handle( http.MethodDelete, "/waiting-list/:ambulanceId/condition", this.DeleteConditions)
   routerGroup.Handle( http.MethodGet, "/waiting-list/:ambulanceId/condition", this.GetConditions)
   routerGroup.Handle( http.MethodPut, "/waiting-list/:ambulanceId/condition", this.UpdateConditions)
 }

 // Copy following section to separate file, uncomment, and implement accordingly
 // // AddConditions - Adds predefined conditions
 // func (this *implAmbulanceConditionsAPI) AddConditions(ctx *gin.Context) {
 //  	ctx.AbortWithStatus(http.StatusNotImplemented)
 // }
 //
 // // DeleteConditions - Deletes all predefined conditions
 // func (this *implAmbulanceConditionsAPI) DeleteConditions(ctx *gin.Context) {
 //  	ctx.AbortWithStatus(http.StatusNotImplemented)
 // }
 //
 // // GetConditions - Provides the list of conditions associated with ambulance
 // func (this *implAmbulanceConditionsAPI) GetConditions(ctx *gin.Context) {
 //  	ctx.AbortWithStatus(http.StatusNotImplemented)
 // }
 //
 // // UpdateConditions - Updates predefined conditions
 // func (this *implAmbulanceConditionsAPI) UpdateConditions(ctx *gin.Context) {
 //  	ctx.AbortWithStatus(http.StatusNotImplemented)
 // }
 //

